### ISSUE TITLE
Where is train.py?

### ISSUE THREAD

**Issue by Mrkkew** [Zhongying-Deng/DIDA#1]
Is the code you have made public complete? Where is the tools/train.py?

**Comment by Zhongying-Deng** [comment]
Thanks for your interest in our work. The code is based on [Dassl codebase](https://github.com/KaiyangZhou/Dassl.pytorch#get-started) and not complete on its own. As stated in  [installation](https://github.com/Zhongying-Deng/DIDA#installation), to use the code in this repo, you will need to first install Dassl codebase via this link https://github.com/KaiyangZhou/Dassl.pytorch#get-started. After installation, you can find tools/train.py.
