### ISSUE TITLE
Detailed operations for dataset of officeHome

### ISSUE THREAD

**Issue by 23425Ning** [Zhongying-Deng/DIDA#2]
Hello! Thanks for ur excellent work! But i did not see any introductions experiments on dataset of officeHome on this github project which u did in ur paper. So I'd ask could u offer some more detailed operations on  how to run ur code on this dataset? Thanks a lot

**Comment by Zhongying-Deng** [comment]
Many thanks for your interest in our work. The config files for OfficeHome have been updated, please find them via [configs/datasets/da](https://github.com/Zhongying-Deng/DIDA/blob/main/configs/datasets/da/office_home.yaml) and [configs/trainers/da/didanet](https://github.com/Zhongying-Deng/DIDA/blob/main/configs/trainers/da/didanet/office_home_dida_single_src.yaml). The backbone used for OfficeHome can be found under [dassl/modeling/backbone](https://github.com/Zhongying-Deng/DIDA/blob/main/dassl/modeling/backbone/resnet_dida_mixstyle.py) (please see the latest updated files for the backbone). For training, please follow the following bash script
```bash
CUDA_VISIBLE_DEVICES=0 python tools/train.py --root ${YOUR_DATA_PATH} --trainer FixMatch \
	--source-domains art --target-domains clipart \
	--dataset-config-file configs/datasets/da/office_home.yaml --config-file configs/trainers/da/didanet/office_home_dida_single_src.yaml \
	--output-dir output/didanet_office_home/art2clipart \
	MODEL.BACKBONE.NAME resnet50_dida_mixstyle TRAIN.CHECKPOINT_FREQ 10
```

I am sorry that I have not debugged these new files, so please feel free to let me know if there are any issues with the experiments on OfficeHome.
